### ISSUE TITLE
Missing wget

### ISSUE THREAD

**Issue by Thefrank** [sec/dotnet-core-freebsd-source-build#1]
`wget` is required by `init.sh`
`wget` is not installed into FreeBSD 12.2 jails and is missing from `install_tools.sh` ;)

edit `fetch` will work instead of using `wget` if you don't want to add another thing to `install_tools.sh`

**Comment by sec** [comment]
Thanks, as long FreeBSD user I should have used `fetch` in first place :) Fixed.
