### ISSUE TITLE
FreeBSD 12 binary for .NET 7

### ISSUE THREAD

**Issue by nkosi23** [sec/dotnet-core-freebsd-source-build#14]
Hello,

Thanks a lot for this work!! I have just seen that you have been able to publish dotnet7 binaries for FreeBSD 13, would you be able to do the same for FreeBSD 12 since it is supported through 2024

Best

**Comment by Thefrank** [comment]
Crossbuilds use FreeBSD 12 docker images.

Servarr team: https://github.com/Servarr/dotnet-bsd
Mine: https://github.com/Thefrank/dotnet-freebsd-crossbuild/

**Comment by sec** [comment]
@Thefrank thanks for reply. @nkosi23 please use Frank's build (I did quick check under 12.3 and it works fine at first glance). 
If you want, you can compile it yourself:
- bootstrap SDK needed to compile v7 using Linux crossbuild (you can use Frank's build for that)
- compile v7 under your FreeBSD 12 box using my scripts/patches
- if you really need native build, let me know I will try to make one in spare moment of time

btw. crossbuild from 12 seems to work fine under 13 also.
