### ISSUE TITLE
Help regarding using Release output from GITHUB

### ISSUE THREAD

**Issue by rupisaini123** [sec/dotnet-core-freebsd-source-build#16]
Hi,

First of all thank you very much for developing this.
As i see your build in Releases of GITHUB. If i want to use those how should i? 
Should i just extract dotnet-sdk*-freebsd-x64.tar.gz and then call dotnet from there?
Or what about the runtime.
Is there any documentation that we can use to run dotnet on freebsd without building our own?
I am new too this, any help will be really appreciated ?

Thanks

**Comment by sec** [comment]
Hi.
Yes, just download proper version for your host (x64 or arm64), either 6 or 7 - the one with "sdk" in name :) extract it somewhere, and call it from there or add to PATH. Runtime is also available for download or you can publish your app as self-contained, it will include FreeBSD runtimes (for that you will either need to download runtimes nupkg or use https://github.com/sec/dotnet-freebsd-nuget-feed as your feed, I'm trying to keep it up-to-date as possible).

Everything is just as normal as using dotnet on either windows or linux, so just read MS docs about that. And as FreeBSD is not supported by MS, use it at your own risk.

**Comment by rupisaini123** [comment]
For now i have just extracted the sdk to folder and can run dotnet command now.
I am trying to publish self-contained but getting this error: Unable to find package Micrsoft.NETCore.App.Runtime.freebsd-x64. No packages exist with this id in source(s): nuget.org [/media/neww/Projects/Projects.sin]
Any Idea what i might be missing?

**Comment by sec** [comment]
Yes, as I wrote before, two options:
1. add `https://sec.github.io/dotnet-freebsd-nuget-feed/v3/index.json` as your NuGet feed
2. download this nupkg from Releases page, put it somewhere and add that location as local nuget feed
