### ISSUE TITLE
Some thoughts on dotnet-libraries

### ISSUE THREAD

**Issue by devosalain** [sec/dotnet-core-freebsd-source-build#20]
Many dotnet libraries have hard-coded "O.S. not supported" when run on FreeBSD.
One example "plotly&xplot"
How to inform all-maintainers of all-dotnet-libraries , dotnet runs now on FreeBSD , and this hard-coding "O.S. not supported" can be removed by eg some simple hooks like location of .dll or .exe files.
I rant about this on the FreeBSD forum.
https://forums.freebsd.org/threads/the-chicken-egg-problem-and-dotnet.88490/
Kind Regards.

**Comment by devosalain** [comment]
Just one simple "ionide" plugin for vscode for f#. It  works with gentoo-linux but on freebsd i see nothing.

**Comment by sec** [comment]
That's something to be taken with 3rd party authors, closing this.
