### ISSUE TITLE
Failed to build 7.0.403

### ISSUE THREAD

**Issue by LTRData** [sec/dotnet-core-freebsd-source-build#22]
Just tried to build 7.0.403 but I get stuck at build_installer.sh and not sure why or what to do about it. (Building 7.0.402 went fine though.)

```
/builds/dotnet7-sdk/installer/src/redist/targets/GenerateLayout.targets(392,5): error : Download from all targets failed. List of attempted targets: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/7.0.403-servicing.23520.31/dotnet-toolset-internal-7.0.403-servicing.23520.31.zip, https://dotnetbuilds.blob.core.windows.net/public/Sdk/7.0.403-servicing.23520.31/dotnet-toolset-internal-7.0.403-servicing.23520.31.zip [/builds/dotnet7-sdk/installer/src/redist/redist.csproj]
##vso[task.logissue type=error;sourcepath=/builds/dotnet7-sdk/installer/src/redist/targets/GenerateLayout.targets;linenumber=392;columnnumber=5;code=;](NETCORE_ENGINEERING_TELEMETRY=Build) Download from all targets failed. List of attempted targets: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/7.0.403-servicing.23520.31/dotnet-toolset-internal-7.0.403-servicing.23520.31.zip, https://dotnetbuilds.blob.core.windows.net/public/Sdk/7.0.403-servicing.23520.31/dotnet-toolset-internal-7.0.403-servicing.23520.31.zip
/builds/dotnet7-sdk/installer/src/redist/targets/GenerateLayout.targets(392,5): error : Failed to download file using addresses in Uri and/or Uris. [/builds/dotnet7-sdk/installer/src/redist/redist.csproj]
##vso[task.logissue type=error;sourcepath=/builds/dotnet7-sdk/installer/src/redist/targets/GenerateLayout.targets;linenumber=392;columnnumber=5;code=;](NETCORE_ENGINEERING_TELEMETRY=Build) Failed to download file using addresses in Uri and/or Uris.

Build FAILED.
```

So, apparently it tries to download https://dotnetcli.blob.core.windows.net/dotnet/Sdk/7.0.403-servicing.23520.31/dotnet-toolset-internal-7.0.403-servicing.23520.31.zip which does not exist. I do not know if it might exist under a slightly different name that can be adjusted here to make it find it or if something is broken online.

**Comment by sec** [comment]
Haven't tried to build latest 7.x yet, but maybe it's just not yet pushed by MS, so waiting is one option.
You could try to build SDK yourself and use what it produce or adjust versions somewhere in Versions.props.

**Comment by LTRData** [comment]
Okay, yes I suppose that could be the reason. 7.0.403/7.0.13 was after all an out-of-band release just to fix a patch mistake in 402/12, so I assume some of the usual procedures could have been missed, or will be carried out later.

Maybe I'll go back to 401/11 for now instead since 402/12 somewhat broke more important things than it fixed.

**Comment by sec** [comment]
I did sdk build (under Linux, it's faster and easier) with `./build.sh -ci /p:OfficialBuildId=20231020.31 -c Release -pack` and got nice 7.0.13 build - will publish them soon.

edit: x64 build is up. arm64 will follow soon(ish).

**Comment by LTRData** [comment]
Thank you! 👍
