### ISSUE TITLE
what do I _do_ with the stuff in release?

### ISSUE THREAD

**Issue by lukeb1961** [sec/dotnet-core-freebsd-source-build#23]
Just a thought. Your Readme might want to mention what people should do with the various files.
Should they unzip to a specific standard location, what to do with the nuget packges, etc.

**Comment by sec** [comment]
There's a port work in the progress - https://github.com/dotnet/runtime/issues/14537#issuecomment-1868513384 - which should put all the bits in place w/build - you can also follow https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install, but you should be familiar with FreeBSD/.net ecosystem, etc. It doesn't make sense for me to rewrite documentation here, but PR's are welcome :)
