### ISSUE TITLE
Missing SSL library?

### ISSUE THREAD

**Issue by Slesa** [sec/dotnet-core-freebsd-source-build#25]
After calling install_tools.sh and init.sh, I get the error msg
  No usable version of libssl was found
for each build_*.sh script. I am running FreeBSD 14.

There is a /usr/lib/libssl.so as well as an /usr/bin/openssl. Is there a symlink missing in /usr/local/lib? But there even exists a /usr/local/lib/libssl3.so?

**Comment by LTRData** [comment]
I saw this also a while ago when trying out FreeBSD 14. I came to the conclusion that the new libssl version in FreeBSD 14 is not recognized. It is more clearly visible when you copy a binary built in FreeBSD 13.x and run it in FreeBSD 14. If I recall correctly it looks for libssl7 but libssl11 is the only one available.

**Comment by sec** [comment]
Can't remember what was the case with building under 14, but my build were done under 13 and they linked with previous openssl version.
There's also port in the works, which should cover this.
Also Frank made this patch https://github.com/Thefrank/freebsd-dotnet-sourcebuild/blob/a4eca45cfbb3eed5dddf2e352264feaf534721ed/PortWIP/dotNET8/files/patch-src_runtime_src_native_libs_System.Security.Cryptography.Native_opensslshim.c that if you want you can try and build with that.
Releases here should work without any problems on 14 (I'm sure I've checked those under 14).

**Comment by sec** [comment]
Here's linked thread about SSL on 14 - https://github.com/Thefrank/freebsd-dotnet-sourcebuild/issues/2#issuecomment-1870124329
