### ISSUE TITLE
Where do I find libgssapi_krb5.so.2.2 for arm64 and x86 on 13.3-RELEASE

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [sec/dotnet-core-freebsd-source-build#31]
Hi, many thanks for the build.

```
packs/Microsoft.NETCore.App.Host.freebsd-arm64/8.0.8/runtimes/freebsd-arm64/native/singlefilehost - required shared library libgssapi_krb5.so.2.2 not found
```

I am missing a shared library, libgssapi_krb5.so.2.2. 

Where can I find it? ( ideally from an existing freebsd binary package )

Thanks,

**Comment by sec** [comment]
`pkg install krb5` should resolve this

**Comment by rhubarb-geek-nz** [comment]
Excellent, thank you
