### ISSUE TITLE
Build failure in v8 branch

### ISSUE THREAD

**Issue by Partmedia** [sec/dotnet-core-freebsd-source-build#34]
I'm on:
```
FreeBSD foxtrot 14.1-RELEASE-p4 FreeBSD 14.1-RELEASE-p4 GENERIC amd64
```
And followed the README instructions, namely:

1. Clone the repo
2. Ran `install_tools.sh`
3. Ran `init.sh`
4. Ran `build_runtime.sh -v d`

The runtime build fails with the following message:

```
Build FAILED.

       "dotnet-core-freebsd-source-build/runtime/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23564.4/tools/Build.proj" (default target) (1) ->
       "dotnet-core-freebsd-source-build/runtime/Build.proj" (Restore target) (3) ->
       (Restore target) -> 
         dotnet-core-freebsd-source-build/runtime/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj : error NU1604: Warning As Error: Project dependency runtime.freebsd-x64.Microsoft.NETCore.Runtime.ObjWriter does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [dotnet-core-freebsd-source-build/runtime/Build.proj]
         dotnet-core-freebsd-source-build/runtime/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj : error NU1101: Unable to find package runtime.freebsd-x64.Microsoft.NETCore.Runtime.ObjWriter. No packages exist with this id in source(s): darc-pub-dotnet-emsdk-0af50f7, darc-pub-dotnet-emsdk-201f4da, darc-pub-dotnet-emsdk-d75f77c, dotnet-eng, dotnet-libraries, dotnet-libraries-transport, dotnet-public, dotnet-tools, dotnet8, dotnet8-transport, ghsec [dotnet-core-freebsd-source-build/runtime/Build.proj]

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:48.12
Build failed with exit code 1. Check errors above.
```
For the repo I'm on the v8 branch (a192e76fe26f).

**Comment by sec** [comment]
Hi,
For building v8 it's easier to use VMR and/or https://www.freshports.org/lang/dotnet/ - there's a port already and my building instructions might not be up-to-date, as I always encounter some errors and don't document all the things :)

**Comment by Partmedia** [comment]
Thanks for the advice. I'll take a look at the port and see if I can get it to do what I want to do. I'm planning on building my own `dotnet/runtime` so that I can troubleshoot the thread pool context switch issue so being able to build from my own runtime source code would help.

**Comment by sec** [comment]
Then best would be to build from ports, it should set everything up - then you can play with the source under `work` dir inside and change/change things.
