### ISSUE TITLE
nuget list update?

### ISSUE THREAD

**Issue by lukeb1961** [sec/dotnet-core-freebsd-source-build#4]
Question: should your nuget_list.txt refer to the rtm pkgs?
Or is that only for RC builds?
Or does it need just rc1?
Wondering how it works.

**Comment by lukeb1961** [comment]
Just notice and wondered if it would matter.

**Comment by sec** [comment]
Hey - take a look at, for example this one - https://github.com/dotnet/runtime/blob/4822e3c3aa77eb82b2fb33c9321f923cf11ddde6/eng/Versions.props#L76 - some nuget's are swaped with patch for rc-1 ones (as we don't have all previous nugets generated) - right now, rc-1 are fine (if you want you can switch them to rc-2 and download them inside nuget directory - it's used during runtime build on some steps). The way it is now, should be fine - from what I can see RTM is still using rc-1 one where not patched :)
