### ISSUE TITLE
missing sudo / sdk not supporting 7 ?

### ISSUE THREAD

**Issue by lukeb1961** [sec/dotnet-core-freebsd-source-build#5]
clean 13 ISO. login as root
1 Run as root install_tools.sh
2 init.sh
3 build_runtime.sh
4 build_installer_without_aspnet.sh

build_installer_without_aspnet.sh fails because installer expects sudo to be installed.
install sudo and try again.. FAILs.

/root/dotnet-core-freebsd-source-build/installer/.dotnet/sdk/6.0.100-rc.2.21505.57/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0. [/root/dotnet-core-freebsd-source-build/installer/src/SdkResolver/SdkResolver.csproj]

**Comment by sec** [comment]
rtm tags got wiped :) fixed in main.
